[project]
name = "ai-llm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "altair==4.2.2",
    "certifi>=2026.1.4",
    "chromadb>=1.4.1",
    "elevenlabs>=2.35.0",
    "faiss-cpu>=1.13.2",
    "langchain-community>=0.4.1",
    "langchain-core>=1.2.9",
    "langchain-ollama>=1.0.1",
    "langchain-text-splitters>=1.1.0",
    "langchain[openai]>=1.2.8",
    "libmagic>=1.0",
    "lxml-html-clean>=0.4.3",
    "newspaper3k>=0.2.8",
    "openai[datalib]>=2.16.0",
    "openai-whisper>=20250625",
    "pandas>=3.0.0",
    "pypdf2>=3.0.1",
    "python-dotenv>=1.2.1",
    "requests>=2.32.5",
    "selenium>=4.40.0",
    "sounddevice>=0.5.5",
    "soundfile>=0.13.1",
    "streamlit>=1.19.0",
    "torch>=2.10.0",
    "transformers>=4.57.6",
    "unstructured>=0.18.31",
    "urllib3>=2.6.3",
    "yt-dlp>=2026.2.4",
    "tiktoken>=0.12.0",
    "datasets>=4.5.0",
    "peft>=0.18.1",
    "evaluate>=0.4.6",
    "fastapi>=0.129.0",
    "uvicorn>=0.40.0",
]

[[tool.uv.index]]
url = "https://nexus.alm.europe.cloudcenter.corp/repository/pypi-public/simple"
default = true
