[project]
name = "ai-llm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "altair==4.2.2",
    "certifi>=2026.1.4",
    "chromadb>=1.4.1",
    "langchain-ollama>=1.0.1",
    "langchain[openai]>=1.2.8",
    "openai>=2.16.0",
    "pandas>=3.0.0",
    "pypdf2>=3.0.1",
    "python-dotenv>=1.2.1",
    "requests>=2.32.5",
    "streamlit>=1.19.0",
    "torch>=2.10.0",
    "transformers>=4.57.6",
    "urllib3>=2.6.3",
]

[[tool.uv.index]]
url = "https://nexus.alm.europe.cloudcenter.corp/repository/pypi-public/simple"
default = true
